Update contributing
kubescape/project-governance pull request #23
Opened 2024-11-27 13:52 UTC by Oshratn

CONTIRBUTING.md updated to reflect CNCF template

2024-11-27 13:56 UTC, Oshratn commented
@slashben before approving, please note that I have two open comments in the CONTRIBUTING.md commit that need to be addressed

2024-11-27 14:25 UTC, slashben requested changes

2024-11-27 14:25 UTC, slashben commented on CONTRIBUTING.md
> +⚠️ **Explain how to set up a development environment**-->
I don't think this is relevant here, it depends on each repo with their own environment setup

2024-11-27 14:25 UTC, slashben commented on CONTRIBUTING.md
> +<!--Ben/Rotem/Matthias this language is from the CNCF suggested template, it incudes much more than we had in the original file, please indicate if something should be removed-->
I am ok with this, we should include these things from the CNCF template (except the one bellow I noted)

2024-11-28 08:16 UTC, Oshratn commented
@slashben completed the requested changes. Ready to merge if you don't see any additional problems.

2024-12-01 06:39 UTC, slashben approved these changes

2024-12-01 08:46 UTC, Oshratn commented
@matthyx @rotemamsa I guess I need your approvals too to merge.

2024-12-01 08:54 UTC, matthyx approved these changes

2024-12-01 09:02 UTC, rotemamsa approved these changes

2024-12-01 09:05 UTC, merged